### ISSUE TITLE
Create configuration on Dynamic Spotter not working

### ISSUE THREAD

**Issue by tormoseng** [CloudScale-Project/Environment#4]
After specifying instrumentation and measurement agents, I go to Configuration. There is a choice there that says "basic configuration". I press on "Create configuration". Nothing happens.

Testet on the nightly build 02.12.15.

**Comment by jurepolutnik** [comment]
Yes, this is a bug. 
You can still create configuration through explorer (right click on Configuration node).

**Comment by jurepolutnik** [comment]
Fixed.
