### ISSUE TITLE
How-to exists on stand-alone DS, not in CSE

### ISSUE THREAD

**Issue by tormoseng** [CloudScale-Project/Environment#6]
Testing the DynSpotter stand-alone gives a Description if an OLB is detected: "A One Line Bridge occurs, if a passive resource limits the concurrency in an application. Passive resources can be ..."

However, running the DynSpotter through CSE only displays a Message stating "# OLB detected in service: org.apache.commons...", but no description. I.e. how-to is missing.

**Comment by jurepolutnik** [comment]
Component needed to be rewritten for CSE and this information has been left out. I will check what can be done...

**Comment by jurepolutnik** [comment]
@tormoseng Can you please attach screenshot. I tested this with Spotter UI and I get the same message.

**Comment by tormoseng** [comment]
Attached are the following figures:
- DS in CSE without any problems
- DS in CSE with a problem
- DS stand-alone with a problem

(note the difference in Description)

![ds_cse_noproblem](https://cloud.githubusercontent.com/assets/5812433/11557949/fce79672-99af-11e5-8437-f80c1a59542e.png)
![ds_cse_withproblem](https://cloud.githubusercontent.com/assets/5812433/11557950/fce8779a-99af-11e5-82aa-36eec5d30510.png)
![ds_standalone_withproblem](https://cloud.githubusercontent.com/assets/5812433/11557951/fcea8288-99af-11e5-8535-2f21edc41f0b.png)

**Comment by jurepolutnik** [comment]
Extensions has been updated after built-in server has been packed (this is not automatic). If you would use external server, you would get new descriptions.  If these was the only changes we will update DS Server package in 3.3.

**Comment by tormoseng** [comment]
Good. I can definitely work with that. :-)

**Comment by jurepolutnik** [comment]
I checked updates to DS and it seems only descriptions has been changing, therefor we will update package in 3.3.

**Comment by tormoseng** [comment]
:+1:

**Comment by jurepolutnik** [comment]
Fixed
